import React from "react";
import Style from "./Styles/Tecnologies.module.css";

export const Tecnologies = () => {
  return (
    <div>
      <h2 className={Style.h2}>➡ Tecnologías</h2>
      <div className={Style.tecnology}>
        <span>
          <img
            src="https://res.cloudinary.com/juan-ardila/image/upload/v1698187206/Folder-Icons/js_oljk8i.png"
            alt="javascript"
          />
          Javascript
        </span>
        <span>
          <img
            src="https://res.cloudinary.com/juan-ardila/image/upload/v1698187197/Folder-Icons/typescript_fwfxwl.png"
            alt="typescript"
          />
          Typescript
        </span>
        <span>
          <img
            src="https://res.cloudinary.com/juan-ardila/image/upload/v1698187201/Folder-Icons/firebase_t77orw.png"
            alt="firebase"
          />
          Firebase
        </span>
        <span>
          <img
            src="https://res.cloudinary.com/juan-ardila/image/upload/v1698187196/Folder-Icons/react_chvcb3.png"
            alt="react"
          />
          ReactJS
        </span>
        <span>
          <img
            src="https://res.cloudinary.com/juan-ardila/image/upload/v1698187196/Folder-Icons/redux_igg4jn.png"
            alt="redux"
          />
          Redux
        </span>
        <span>
          <img
            src="https://res.cloudinary.com/juan-ardila/image/upload/v1698187204/Folder-Icons/HTML5_st6ckd.png"
            alt="HTML5"
          />
          HTML5
        </span>
        <span>
          <img
            src="https://res.cloudinary.com/juan-ardila/image/upload/v1698187198/Folder-Icons/CSS_d6hazs.png"
            alt="CSS"
          />
          CSS
        </span>
        <span>
          <img
            src="https://res.cloudinary.com/juan-ardila/image/upload/v1698187200/Folder-Icons/express_rfco3l.png"
            alt="express"
          />
          ExpressJS
        </span>
        <span>
          <img
            src="https://res.cloudinary.com/juan-ardila/image/upload/v1698187192/Folder-Icons/node_abp1qu.png"
            alt="NodeJS"
          />
          NodeJS
        </span>
        <span>
          <img
            src="https://res.cloudinary.com/juan-ardila/image/upload/v1698187202/Folder-Icons/git_gvrcip.png"
            alt="git"
          />
          git
        </span>
        <span>
          <img
            src="https://res.cloudinary.com/juan-ardila/image/upload/v1698187203/Folder-Icons/github_assghd.png"
            alt="github"
          />
          gitHub
        </span>
        <span>
          <img
            src="https://res.cloudinary.com/juan-ardila/image/upload/v1698187194/Folder-Icons/postgresql_c4ddbf.png"
            alt="postgresql"
          />
          PostgreSQL
        </span>
        <span>
          <img
            src="https://res.cloudinary.com/juan-ardila/image/upload/v1698187192/Folder-Icons/mysql_de5uwu.png"
            alt="mysql"
          />
          MySQL
        </span>
        <span>
          <img
            src="https://res.cloudinary.com/juan-ardila/image/upload/v1698187195/Folder-Icons/python_bod3wn.png"
            alt="python"
          />
          Python
        </span>
      </div>
    </div>
  );
};
